spring:
  application:
    name: blogging-system

  datasource:
    url: jdbc:mysql://localhost:3306/blogging_system
    username: root
    password: validsam123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: "brainsam056@gmail.com"
    password: "qbdbpkrhfdegbxfo"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: false



server:
  port: 8800
